### ISSUE TITLE
channel name does support Chinese

### ISSUE THREAD

**Issue by steve1412** [nminchow/Voltaire#1]
In the following command, the channelname couldn't be in Chinese. although the rest is fine.
> !volt send_guild "servername" channelname sometext

**Comment by nminchow** [comment]
@steve1412 - could you verify this is still an issue? I updated the bot's framework and and it fixed a couple of these weird localization issues.

**Comment by steve1412** [comment]
Hey,

This is fine now many thanks

在 2019年3月21日，下午10:43，Noel Minchow <notifications@github.com<mailto:notifications@github.com>> 写道：


@steve1412<https://github.com/steve1412> - could you verify this is still an issue? I updated the bot's framework and and it fixed a couple of these weird localization issues.

**Comment by nminchow** [comment]
🎉
