### ISSUE TITLE
Non standard ASCII formating does not compute

### ISSUE THREAD

**Issue by zedansk** [nminchow/Voltaire#13]
If you have "fancy" servernames or channel names Voltaire cant find the channel or even the server. As an example if a channel is named ỼօӀէąìɾe it wont work even if you copypaste it into DM. Not really an issiue but worth noted were many servers use this kinds of names for channels, same goes for any non standard ascii text and emojis. "bugtested" this by trying diffrent combinations and its reacting even if its just one symbol.

**Comment by nminchow** [comment]
Thanks for the report! Its surprising that the command string would be coming in with different encoding than the api returns for channel/server names, but it is possible. There must be something weird going on. Hopefully this is easy to normalize.

**Comment by nminchow** [comment]
@zedansk - I'm having trouble recreating. With a server and channel name of "ỼօӀէąìɾe", the following works:
![image](https://user-images.githubusercontent.com/7690508/55685881-a09d4e00-5920-11e9-8f81-c8474ec91ad6.png)

Could there be any other special conditions that are causing this to fail?

**Comment by zedansk** [comment]
write to me on Discord boof#1312 I have tried multible configs without success. also the way the output from the bot in konsole speaks the same language

**Comment by nminchow** [comment]
unable to recreate, closing for now
