### ISSUE TITLE
`QueryForSubscription` using `List` instead of `ListAutoPaging`

### ISSUE THREAD

**Issue by nivekastoreth** [nminchow/Voltaire#31]
After being blindsided by the paywall (that is not mentioned anywhere outside of the source code), I started looking at the code enforcing it, and noticed that your logic for determining if someone has a `subscriptionId` will likely break after 100 guilds.

**Comment by nminchow** [comment]
@nivekastoreth - Thanks for the issue!

After querying the 100 most recent subscriptions, we save the matched subscription [here](https://github.com/nminchow/Voltaire/blob/6ea96db6b38d49616145295ad7ce4483c5a491d0/Voltaire/Controllers/Helpers/EnsureActiveSubscription.cs#L54). So, in order for the limit to actually break anything, a guild would need to upgrade to pro and then never utilize any features that do the `pro` check before 100 more subscriptions were crated. While possible, I don't think this will occur any time soon.

**Comment by nminchow** [comment]
Closing for now. Will reopen is issue arises.
