### ISSUE TITLE
[CRITICAL] Security issue in bot

### ISSUE THREAD

**Issue by thepwrtank18** [nminchow/Voltaire#62]
![image](https://github.com/nminchow/Voltaire/assets/57580668/5ce6fdac-a105-446f-8676-85be2023b395)

**Comment by NOTPIES** [comment]
wink

**Comment by nminchow** [comment]
Hey, just doing some triage here. Can you explain the issue? This looks like someone using the bot to ping `@everyone` in a server where the bot is allowed to do so.

**Comment by thepwrtank18** [comment]
it's been almost a year i forgot all about this

**Comment by nminchow** [comment]
It has, I appreciate the reply. Is it still something you'd like me to take a look at?

**Comment by thepwrtank18** [comment]
Unless something like this shows up again, not really a problem right now :P

**Comment by nminchow** [comment]
Sure - can you explain what the security issue was, or should I close?

**Comment by thepwrtank18** [comment]
Considering how long ago it was (and that I'm not on the server the event took place in anymore), I can't say for myself
